# Generated by Django 3.2.4 on 2021-06-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('catname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('catimage', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='pics')),
                ('product_price', models.IntegerField()),
                ('soldby', models.CharField(max_length=200)),
                ('catna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.category')),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('subcatname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('catnam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.category')),
            ],
        ),
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('related_to', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_weight', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcatname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.subcategory'),
        ),
    ]
