# Generated by Django 3.2.4 on 2021-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0004_auto_20210612_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
