# Generated by Django 3.2.4 on 2021-06-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_alter_userdetails_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.userdetails')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.product')),
            ],
        ),
    ]
