# Generated by Django 3.2.4 on 2021-06-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0008_paymentdetails_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='negotiationdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('negotaited_price', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.userdetails')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.product')),
            ],
        ),
    ]
