# Generated by Django 3.2.4 on 2021-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0009_auto_20210616_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
