# Generated by Django 3.2.4 on 2021-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0013_alter_cart_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationdetails',
            name='negotiated_date',
            field=models.DateField(auto_now_add=True)
           
        ),
    ]
