# Generated by Django 3.2.4 on 2021-06-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0014_negotiationdetails_negotiated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiationdetails',
            old_name='negotaited_price',
            new_name='negotiated_price',
        ),
    ]
