# Generated by Django 3.2.4 on 2021-06-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0015_rename_negotaited_price_negotiationdetails_negotiated_price'),
        ('adminmodule', '0016_auto_20210618_2019'),
    ]

    operations = [
    ]
