# Generated by Django 3.2.4 on 2021-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0017_merge_20210618_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
