# Generated by Django 3.2.4 on 2021-06-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0019_auto_20210618_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
