# Generated by Django 3.2.4 on 2021-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0025_auto_20210626_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
