# Generated by Django 3.2.4 on 2021-07-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0027_recentlyviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.userdetails')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.product')),
            ],
        ),
    ]
