# Generated by Django 3.2.4 on 2021-07-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0029_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('stars', models.IntegerField()),
                ('suggestion', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.userdetails')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.product')),
            ],
        ),
    ]
